config/routes.rb
Rails.application.routes.draw do
 root 'posts#index', as: 'home'
 
 get 'about' => 'pages#about', as: 'about'

 resources :posts do
   resources :comments
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :title, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coments_controller.rb
class ComentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to posts_path(@post)
  end

  private 
  def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @heading = 'Сорінка про нас'
    @text = 'Трішки тексту'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "1q2", except: [:index, :show]

  def index
    @post = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    
    if(@post.update(post_params))
    redirect_to @post
    else 
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def create
    #render plain: params[:post].inspect
    @post = Post.new(post_params)

    if(@post.save)
    redirect_to @post
    else 
      render 'new'
    end
  end

  private 
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coments_helper.rb
module ComentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"%>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <div class="container py-3">
     <header>
       <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
         <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
           <span class="fs-4 font-weight-bold">SimpleBlog</span>
         </a>

         <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
           <span class="me-3 py-2 text-dark text-decoration-none"> <%= link_to "Головна сторінка", home_path %></span>
           <span class="me-3 py-2 text-dark text-decoration-none"> <%= link_to "Написати статтю", new_post_path %></span>
           <span class="me-3 py-2 text-dark text-decoration-none"> <%= link_to "Про нас", about_path %></span>
         </nav>
         </div>
      </header>
    </div>

    <div class="container">
    <%= yield %>
    </div>
    
  </body>
</html>

app/views/pages/about.html.erb
<h3><%= @heading %></h3>
<p><%= @text %></p>

app/views/posts/edit.html.erb
<h2>Редагування поста</h2>
<%= form_for :post, url: post_path(@post), method: :patch  do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>%>
  <% end %>
  <p>
  Назва<br>
  <%= f.text_field(:title, {:class => 'form-control'}) %>
 </p>

 <p>
  Текст статті<br>
  <%= f.text_area(:body, {:class => 'form-control'}) %>
 </p>

 <p>
  <%= f.submit({:class => 'btn btn-success'})%>
 </p>
<% end %>

app/views/posts/index.html.erb
<h1>Всі наші пости</h1>
<% @post.each do |post| %>
  <div class="alert alert-light">
    <h3><%= post.title %></h3>
    <p><%= post.body %></p>
    <%= link_to "Читати далі", post_path(post), :class => 'btn btn-outline-primary' %>
   </div>
   
<% end %>

app/views/posts/new.html.erb
<h2>Додаємо новий пост</h2>
<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>%>
  <% end %>
  <p>
  Назва<br>
  <%= f.text_field(:title, {:class => 'form-control'}) %>
 </p>

 <p>
  Текст статті<br>
  <%= f.text_area(:body, {:class => 'form-control'}) %>
 </p>

 <p>
  <%= f.submit({:class => 'btn btn-success'})%>
 </p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<hr>
<%= link_to "Редагувати", edit_post_path(@post), :class => 'btn btn-warning'%>
<%= link_to "Видалити пост", posts_path(@post), method: :delete, data: {confirm: "Бажаєте видалити статтю?"}, :class => 'btn btn-danger'%>

<hr>
<h2>Всі коментарі</h2>
<% @post.comments.each do |comment| %>
  <div class="alert alert-light">
    <p><strong><%= comment.username %></strong>: <%= comment.boby %></p>
  </div>
<% end %>

<hr>
<h2>Додати коментар</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
  Користувач<br>
  <%= f.text_field(:username, {:class => 'form-control'}) %>
 </p>

 <p>
  Текст коментаря<br>
  <%= f.text_area(:body, {:class => 'form-control'}) %>
 </p>

 <p>
  <%= f.submit("Добавити коментар", {:class => 'btn btn-warning'})%>
 </p>
<% end %>